<?php
return [
		1=>['Lyssna - uppmärksamma den som talar, försök förstå','Starta ett samtal - börja samtalet om ett ämne som leder över till ett annat','Föra ett samtal - tala om sådant som intresserar båda','Fråga - bestämma vilken information som behövs','Säga tack - låta andra förstå att man är tacksam','Presentera sig själv - på eget initiativ bli bekant med andra','Presentera andra - hjälpa andra att bli bekanta','Ge komplimanger - berätta att man uppskattar något hos andra'
		],
		2=>['Be om hjälp - fråga om assistans vid svårigheter',' Ta initiativ till att vara med - besluta om att bli delaktig i en pågående aktivitet','Ge instruktioner - tydligt förklara för andra hur de skall gå tillväga med en uppgift',' Följa instruktioner - uppmärksamma och följa andras instruktioner',' Be om ursäkt - berätta för andra att man är ledsen över att ha gjort något','Övertyga andra - övertyga andra om att den egna idén är bättre än deras'
		],3=>['Vara medveten om sina känslor - känna igen egna känslor','Uttrycka sina känslor - låta andra få veta egna känslor','Förstå andras känslor - komma underfund med vad andra känner ',' Handskas med andras ilska - förstå andras känslor av ilska	','Uttrycka tillgivenhet - bry sig om andra','Handskas med rädsla - klara ut varför man är rädd för något, reducera rädslan	','Belöna sig själv - säga eller göra något trevligt åt sig själv']
		,4=>['Be om tillåtelse - utröna när man behöver tillåtelse till något och be om denna','Dela med sig - dela med sig till någon	',' Hjälpa andra - assistera den som behöver hjälp	','Förhandla - att nå fram till en plan som tillfredsställer en själv och andras avvikande uppfattning	 ','Behärska sig - kontrollera det egna humöret	','Hävda sina sina rättigheter - låta andra få veta den egna ståndpunkten',' Bemöta retsamma kommentarer - bibehålla kontrollen när man blir retad',' Undvika bråk med andra - hålla sig utanför situationer som kan leda till gräl	',' Undvika slagsmål - fundera ut alternativ till bråk för att klara ut besvärliga situationer']
		,5=>['Framföra klagomål och  kritik - tala om för andra att de är ansvariga för ett problem, uppmana andra att söka','Bemöta klagomål och kritik - att försöka finna en lösning på ett problem någon annan uppmärksammat','Uppträda sportsligt - vid tävlan erkänna att annan gjort en bra insats',' Handskas med generande situationer - vara mindre generad och självmedveten','Handskas med att bli lämnad utanför - bli varse åsidosättning och bibehålla fattningen',' Försvara en kamrat - låta andra få veta när en vän blivit illa behandlad ','Bemöta övertalning - uppmärksamma annans ståndpunkt och göra jämförelse med egen','Hantera misslyckanden - utröna skäl till misslyckanden och vad som måste göras annorlunda',' Handskas med dubbla budskap - uppmärksamma och handskas med oklarheter och dubbla budskap','Bemöta anklagelser - bli varse när man blir anklagad, besluta om bästa sätt att handskas med detta',' Förbereda sig för ett svårt samtal samtal - planera bästa sätt att genomföra ett obehagligt samtal',' Hantera grupptryck - bortse från vad andra vill när man skall ta ett beslut']
		,6=>['Ta sig för något - sätta igång en aktivitet','Ta reda på orsaken till ett problem - finna ut vad som orsakar något som ligger utanför egenkontroll',' Ställa upp mål - besluta vad som är realistiskt att uppnå innan en uppgift påbörjas','Bedöma vad man är bra på - bli varse egna möjligheter och begränsningar att genomföra något','Samla information - bedöma vad man behöver veta och hur man får reda på det',' Rangordna problem - arrangera problem efter deras betydelse och ta itu med det viktigaste först',' Fatta beslut - överväga möjligheter och välja bästa alternativ',' Koncentrera sig på en uppgift - göra de förberedelser som behövs för att genomföra en uppgift']
];