<?php
return [
	'Samtycke till placeringen'=>['Barnet samtycker till placeringen','Vårdnadshavare samtycker till placeringen'],
	'Utskrivning'=>['Utskriven enligt planering, uppdraget slutfört','Sammanbrott i vid mening före måluppfyllelse (utskriven med överenskommelse, ingen idé att fortsätta)','Tydligt sammanbrott (i strid med socialtjänstens önskemål eller efter socialtjänstens missnöje)'],
	'Försvårande problematik relaterat till barnet vid placering'=>['Invandrarbakgrund minst en av föräldrarna är född utomlands','Ensamkommet barn till Sverige','Bristande språkförmågor','Icke fungerande skolgång','Problematiska kamratrelationer','Saknar organiserade fritidsaktiviteter, med prosociala kamrater','Trotsighet, ilska och oräddhet','Överaktivitet, impulsivitet, koncentrationssvårigheter','Svårighet med medkänsla skuld elller ånger','Självskadebeteende, barnet skadar avsiktligt sin kropp t.ex. genom att skära eller bränna sig','Negativa problemlösningar, tolkningar och attityder','Nedstämdhet','Normbrytande, provoserande beteenden','Kriminalitet, barnet har begått flera brott eller enstaka allvarliga brott','Alkoholanvändning','Drogmissbruk, inklusive sniffning och ej ordinerad medicin','Barnet har en diagnos t.ex. ADHD, Asperger, Tourette, utvecklingsstörning eller psykiska problem i form av depression, suicidförsök, ätstörning','Barnet har mer än en diagnos t.ex. ADHD, Asperger, Tourette, utvecklingsstörning eller psykiska problem i form av depression, suicidförsök, ätstörning','Barnet tar inte ordinerad medicin','Barnet har problem av allvarlig grad i form av hög frånvaro eller beteendeproblem i förskolan eller skolan','En allvarlig eller flera polisrapporter om misshandel alternativt upprepat eller allvarligt våld i skolan, hemmet eller på fritiden','Barnet utsätter sig för farliga eller olämpliga kontakter via nätet','Barnet ägnar så stor tid till nät- eller dataaktiviteter att annat i barnets utveckling blir lidande','Barnet prostituerar sig, har ett gravt sexuellt avvikande beteende t.ex. begår övergrepp mot andra barn, har ett mycket sexuellt utmanande beteende','Normbrytande vänner, barnet umgås med vänner som bryter mot samhällets normer t.ex. missbrukar eller begår kriminella handlingar','Placeringen motiveras av att barnet har speciella omsorgsbehov som inte kan tillgodoses i hemmet t.ex. utifrån psykiska problem eller stora somatiska problem'],
	'Försvårande erfarenheter hos barnet'=>['Tidigare placerad i dygnsvård','Tidigare placerad inom § 12-vård','Tidigare utredning av socialtjänsten innan den utredning som föranledde placeringen','Tidigare öppenvård inom socialtjänsten','Långvarigt missbruk hos förälder eller annan i barnets uppväxtmiljö','Långvarig psykisk sjukdom hos förälder eller annan i barnets uppväxtmiljö','Sexuella övergrepp eller ofredande, eller misstanke härom, under uppväxten','Misstanke eller konstaterand fysisk eller psykisk misshandel i hemmiljön','Kriminell person i barnets hemmiljö under uppväxten, personen har gjort flera små eller enstaka grova brott','Våld i familjen under uppväxten som inte varit riktat mot barnet','Förälder med funktionsnedsättning som påverkat utövandet av föräldraskap','Förälder med begåvningsmässig funktionsnedsättning under uppväxten','Allvarliga konflikter mellan föräldrar, föräldrar har haft stora svårigheter att komma överens om frågor som rör barnet','Icke fungerande skolgång','Ekonomiska problem i hemmiljön ex kronofogde eller långvarigt försörjningsstöd','Arbetslöshet, om minst en av barnets föräldrar har mindre än 50 % arbete'],
	'Försvårande omständigheter vid placeringen'=>['Placeras med stöd av LVU','Barnets hem är < 10 mil från placeringen','Barnet samtycker ej till vården','Vårdnadshavare 1 samtycker ej till vården','Vårdnadshavare 2 samtycker ej till vården','Påbörjas placering i samband med att föregående placering avslutas','Akut placering'

	],
	'Motiv till placeringen'=>['Utstötning, vårdnadshavare eller vårdgivare vägrar låta barnet bo kvar','Rymning, barnets återkommande rymningar anges som skäl till placeringen','Vårdnadshavare har lämnat barnet hemma och bor på annan ort, sitter i fängelse eller är på sjukhus','Det finns allvarliga misstankar om eller har konstaterats att barnet utsatts för sexuella övergrepp','Det finns allvarliga misstankar om eller har konstaterats att barnet utsatts för psykisk eller fysisk misshandel','Barnet utsätts för psykisk, social och fysisk bestraffning som är kollektivt accepterat utifrån ett hederstänkande','Relationsproblem i den biologiska familjen, barnet och föräldern/föräldrarna har levt i en långvarig konflikt','Familjerättslig konflikt, barnet bedöms skadas av föräldrarnas konflikt eller egenmäktigt förfarande med barn','Omvårdnad och tillsyn brister t.ex. får inte tillgång till mat, behandlas illa, får ej möjlighet till vila','Barnet får inte medicinsk vård, får inte skydd mot olycksfall eller skadlig exponering i den miljö denne befinner sig','Eget beteende, barnets utagerande sätt mot omgivningen','Eget beteende, barnet använder självskadebeteenden','Eget beteende, barnet isolerar sig','Eget beteende, barnet skolkar','Eget beteende, barnet vagabonderar','Eget beteende, barnet utsätter sig för faror på nätet','Eget beteende, barnets sexuella aktiviteter','Eget beteende, barnet vänder på dygnet','Eget beteende, barnet dricker alkohol','Eget beteende, barnet missbrukar oföreskrivna läkemedel eller andra droger']

];
